In [2]:
from bs4 import BeautifulSoup as bs

content = []
# Read the XML file
with open("1791_Purm_Louw_kopie_tei.xml", "r", encoding= 'utf-8') as file:
    # Read each line in the file, readlines() returns a list of lines
    content = file.readlines()
    # Combine the lines in the list into a string
    content = "".join(content)
    bs_content = bs(content, "lxml")

In [3]:
everything_results = bs_content.find_all("l")

In [4]:
dict_list = list()
n = 0
for item in list(everything_results):
    item_string = str(item)
    temp_dict =dict()
    n+=1
    if '<kopie>' in item_string:
        temp_dict['text'] = item.text
        temp_dict['index']= n
        temp_dict['kopie']= 1
        dict_list.append(temp_dict)
    else:
        temp_dict['text'] =item.text
        temp_dict['index'] = n
        temp_dict['kopie'] = 0
        dict_list.append(temp_dict)
#print(len(dict_list))
#print(dict_list[0:10])

'''I like this list of dicts and it gives me everything I need, but Im still not sure if the kopies line up between this and 
the find_all(kopie) method. In theory they should because everythings is first tagged as a linebefore a nested kopie tag
...The difference in length between the two is 27'''

dict_kopie_list = list()
for temp_dict in dict_list:
    if temp_dict['kopie'] == 1:
        dict_kopie_list.append(temp_dict['text'])
        
#print(len(dict_kopie_list))
#print(len(line_content_K))

#print(len(set(dict_kopie_list)-(set(line_content_K))))
'''there are 119 kopies which are not shared between the texts. This is different from their difference in length being 27...'''
kopie_indices = list()
for temp_dict in dict_list:
    if temp_dict['kopie'] == 1:
        kopie_indices.append(temp_dict['index'])
#print(kopie_indices)
'''unlike in the original attempt, here the indices line up perfectly e.g. consecutive lines which are copied have
consecutive indices.'''

'unlike in the original attempt, here the indices line up perfectly e.g. consecutive lines which are copied have\nconsecutive indices.'

In [5]:
import pandas as pd

new_df = pd.DataFrame(dict_list)

In [6]:
'''want to compare each row in the new_df and find consecutive rows with the same value for kopie and consecutive indices.
These should be grouped together to form a second df where the text column is a string of all the lines that meet this filter
joined together into one text chunk, kopie column is still 0/1 and index column is the list of line indices included in that 
text chunk'''
new_df

       index  kopie                                               text
0          1      0                                       [afbeelding]
1          2      0                                            Vervolg
2          3      0                                                der
3          4      0                                            kronijk
4          5      0                                                van
5          6      0                                         Purmerende
6          7      0                                            als een
7          8      0                                        tweede deel
8          9      0                               bevattende de jaaren
9         10      0                                      1766 tot 1774
10        11      0                                        eerste stuk
11        12      0                                         Voorberigt
12        13      0                               Veel Geachte Burgers
13        14      0                               der Stad Purmerende,
14        15      0             Ik breng Uw weder alhier onder het oog
15        16      0           een vervolg op de Kronijk van Purmerende
16        17      0            door mijn beschreven, konnende dese als
17        18      0      een Tweede deel, of vervolg, van het aenmerk¬
18        19      0    waerdigste binnen de korte tijd van elf jaeren,
19        20      0      van 1766 tot het eijnde van 't jaar 1777 bin¬
20        21      0           nen deze stad voorgevallen, dienen Mijne
21        22      0          gedagten waren om het bij het Eerste deel
22        23      0         der kronijk of geschiedenisse dezer stadt,
23        24      0          het te laeten berusten, maar de voornaeme
24        25      0      en buijtengewoone voorvallen, dewelke in deze
25        26      0          korte tijdkring alhier zijn gebeurt, heb¬
26        27      0           ben mijn verpligt, om de pen weder op te
27        28      0           vatten, om daer door geduurig, eene aan¬
28        29      0              genaeme nagedagtenisse, in ons geheu¬
29        30      0              gen te doen herleeven, Het voornaems¬
...      ...    ...                                                ...
45095  45096      0          geweest dewelke door de Slegte vangst, de
45096  45097      0            Premien getrokken hebben, bestaande in
45097  45098      0      Ƒ 50 Guld: voor ijder kwardeel Traan het welk
45098  45099      0     ijder Schip beneden de 100 kwardeelen gevangen
45099  45100      0    had; Het welk aan 't Land ruim 1,50,000 Guldens
45100  45101      0   gekost heeft, met die van St: Davids daar bijge¬
45101  45102      0           rekend Groenland bedr: Ƒ 114850 : -  : -
45102  45103      0                      en St Davids van de 15 Schep:
45103  45104      0                       11 Trekkende Ƒ 46050 : - : -
45104  45105      0                       dus te zamen Ƒ 160900 : - :-
45105  45106      0           Onder deze 45 redereijen zoo van Groenl.
45106  45107      0         als Str Davids, zijn 'er 15 geweest die de
45107  45108      0  volle premie van Ƒ 5000 guld: en 9 die tot  Ƒ ...
45108  45109      0        en daar boven Schaevergoeding genooten had,
45109  45110      0          Nogthans hadden de Reders van deze Schep:
45110  45111      0          Voor dit Jaar nog meer dan 4 Tonnen Gouds
45111  45112      0     uijt haare eijgene Beurs daar bij laet  zitten
45112  45113      0        door Mis Credit van de Wisselbank tot Am@@@
45113  45114      0             was het Bankgeld gedaald tot Ƒ 4 Guld:
45114  45115      0       van de Ƒ 100 Guld: beneden het Casgeld in 't
45115  45116      0            Jaar 1791 Het geene eene groote Confus@
45116  45117      0               in de Koophandel en Wissel Cours gaf
45117  45118      0               waar op die Stad eene Negotiatie van
45118  45119      0          6 Millioen: Guld: tegens 3 ½ gld pr Cents
45119  45120      0             Ter Stads Thezauriere voor de tijd van
45120  45121      0         12 Jaaren of 6 Jaaren na goed vinden af te
45121  45122      0              lossen genegotiëerd heeft in de Maand
45122  45123      0            Junij 1791 was het Credit van het Bank¬
45123  45124      0      geld a la pari, of gelijk tegens het Casgeld;
45124  45125      0                                                898

[45125 rows x 3 columns]

In [7]:
'''Double checking the number of kopies vs non-kopies in new_df'''
kopie_freqs=new_df['kopie'].value_counts()
kopie_freqs_df = pd.DataFrame(kopie_freqs.iteritems(), columns =['Kopie', 'Freq',])
kopie_freqs_df

   Kopie   Freq
0      0  39943
1      1   5182

In [8]:
'''working on grouping from new_df'''

'''seperating kopies and non-kopies into seperate dfs'''
kopie_bool = new_df['kopie'] == 1
kopie_df = new_df[kopie_bool]
#print(kopie_df[0:5])
no_kopie_bool = new_df['kopie'] == 0
no_kopie_df = new_df[no_kopie_bool]
#print(no_kopie_df[0:5])

'''finding groups of consecutive indices in each seperated df'''
def ranges(nums):
    nums = sorted(set(nums))
    gaps = [[s, e] for s, e in zip(nums, nums[1:]) if s+1 < e]
    edges = iter(nums[:1] + sum(gaps, []) + nums[-1:])
    return list(zip(edges, edges))

index_groups_kopie = ranges(kopie_df['index'])
index_groups_no_kopie = ranges(no_kopie_df['index'])

In [17]:
'''Using the index group ranges (list of tuples) to find the rows from the corresponding indices in new_df'''
#kopie_main_list = list()
#for group in index_groups_kopie:
#    grouping_dict = dict()
#    text_list = list()
#    for index, row in new_df.iterrows():
#        for i in range (group[0],group[1]+1):
#            if row['index'] == i:
#                text_list.append(row['text'])
#    grouping_dict['text_list'] = text_list
#    grouping_dict['index_range'] = group
#    grouping_dict['kopie'] = 1
#    kopie_main_list.append(grouping_dict)
    
#print(kopie_main_list[0:2])
'''the above method is much too slow to give results'''
#kopie_main_list =list()
#for group in index_groups_kopie:
#    grouping_dict =dict()
#    grouping_dict['index_range'] = group
#    grouping_dict['kopie'] = 1
#    text_list =list()
#    for index, row in new_df.iterrows():
#        if row['index'] in range (group[0], group[1]+1):
#            text_list.append(row['text'])
#    grouping_dict['text_list'] = text_list
#    kopie_main_list.append(grouping_dict)
            
#print(kopie_main_list[0:2])
''' the above method is also too slow to produce results. Try to break this in two and use the .loc or .index pandas function
to find each of the rows first before taking the infomration from them.Like in dig_hum.'''
loc_main_K = list()
for group in index_groups_kopie:
    loc_group_dict =dict()
    loc_group_dict['index_range'] = group
    loc_list = list()
    for i in range (group[0],group[1]+1):
        loc_list += list(new_df.loc[new_df['index'] == i].index)
    loc_group_dict['loc_list'] = loc_list
    loc_main_K.append(loc_group_dict)
    
#print(loc_main_K[0:2])

loc_main_NK = list()
for group in index_groups_no_kopie:
    loc_group_dict =dict()
    loc_group_dict['index_range'] = group
    loc_list = list()
    for i in range (group[0],group[1]+1):
        loc_list += list(new_df.loc[new_df['index'] == i].index)
    loc_group_dict['loc_list'] = loc_list
    loc_main_NK.append(loc_group_dict)
    
#print(loc_main_NK[0:2])

In [48]:
'''Now we have two list of dicts, one for kopie and one for non-kopie. For each the dicts consist of index_range which is the
line index range and should be preserved an included and loc_list which is the list of row locations which the text needs to 
be collected from in new_df for that chunk.'''
K_list = list()
for group_dict in loc_main_K:
    temp_dict = dict()
    group_text = list(new_df.loc[group_dict['loc_list'], 'text'])
    temp_dict['index_range'] = group_dict['index_range']
    temp_dict['kopie'] = 1
    temp_dict['text_list'] = "".join(group_text)
    K_list.append(temp_dict)
    
#print(K_list[0:3])

NK_list = list()
for group_dict in loc_main_NK:
    temp_dict = dict()
    group_text = list(new_df.loc[group_dict['loc_list'], 'text'])
    temp_dict['index_range'] = group_dict['index_range']
    temp_dict['kopie'] = 0
    temp_dict['text_list'] = "".join(group_text)
    NK_list.append(temp_dict)
    
#print(NK_list[0:3])

In [49]:
'''combining the two lists of dicts'''
whole_list= K_list+NK_list
#print(type(whole[0]))
print(whole_list[0])

{'index_range': (73, 90), 'kopie': 1, 'text_list': "woorden, Nooijt stond ik, om dit in t'voorbij gaan te melden, meer verzet,over hun lieden, Namentlijk de Bur¬gereij, Konst en Smaak, in dit op¬zigt, dan bij de laaste komste vanzijne doorl: Hoogheijd ter steedePurmerende, de Geheele Stadt waseen Lustpriëel, de Konstige Eere¬Poorten, bestaande uijt Palm enBloemen, aan Latwerk gevlogten,en de Groene Slingers, die men kruijs¬wijze van huijs tot huijs, dwars overde Straeten, welke met Palm enBloemen bestrooyd waeren Gevlog¬ten had, maakten dat men eer dooreen doorgaende Berceau of eene Gaen¬dereij van vroolijk groen, dan in eenestadt scheene te wandelen; /1/ ver¬"}

In [50]:
whole_df =pd.DataFrame(whole_list)

In [51]:
whole_df.shape

(609, 3)

In [52]:
whole_df[0:10]

  index_range  kopie                                          text_list
0    (73, 90)      1  woorden, Nooijt stond ik, om dit in t'voorbij ...
1  (235, 235)      1          Wat het Eerste betreft, dat er eene Meer¬
2  (238, 330)      1  Omtrent het Jaer 1400 onder de Re¬geringe van ...
3  (351, 357)      1  hier over het volgende "Meermin, Sijreene,is e...
4  (428, 445)      1  zelve gezien hebben "Men vind in¬de Kronijk va...
5  (450, 487)      1  in 't 1548, heeft Philippus Aartshertogvan Oos...
6  (494, 497)      1  Meermin, daar men zoo veele Fabulenen verdigts...
7  (510, 537)      1  en Gevangen is; de Meerminnen zijnAgt spannen ...
8  (540, 559)      1  Indiäenen braeden deze Visch op eenRooster, en...
9  (595, 631)      1  Met Permissie enz:Werd bekend gemaakt dat alhi...